// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgO9wAhq8K_XMprbyKU0cpUG7sa7mo2cw',
    appId: '1:32850116552:web:f6aacef9fa6d5c8be5cafd',
    messagingSenderId: '32850116552',
    projectId: 'magno-opus-9680e',
    authDomain: 'magno-opus-9680e.firebaseapp.com',
    storageBucket: 'magno-opus-9680e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3cMZYdpiuz2OjfAi4s0vJk7wFqgFjVco',
    appId: '1:32850116552:android:ed40c6da4fc64e64e5cafd',
    messagingSenderId: '32850116552',
    projectId: 'magno-opus-9680e',
    storageBucket: 'magno-opus-9680e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh08Z6P11RiR4vJu2hGvq0V-Jp_8tKl7g',
    appId: '1:32850116552:ios:20e872b7cb4a2c93e5cafd',
    messagingSenderId: '32850116552',
    projectId: 'magno-opus-9680e',
    storageBucket: 'magno-opus-9680e.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh08Z6P11RiR4vJu2hGvq0V-Jp_8tKl7g',
    appId: '1:32850116552:ios:20e872b7cb4a2c93e5cafd',
    messagingSenderId: '32850116552',
    projectId: 'magno-opus-9680e',
    storageBucket: 'magno-opus-9680e.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgO9wAhq8K_XMprbyKU0cpUG7sa7mo2cw',
    appId: '1:32850116552:web:60fafb5a04cb2c3de5cafd',
    messagingSenderId: '32850116552',
    projectId: 'magno-opus-9680e',
    authDomain: 'magno-opus-9680e.firebaseapp.com',
    storageBucket: 'magno-opus-9680e.firebasestorage.app',
  );
}
