// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Cml1bGTaoH24MDMDQ83YWGJsFTkIe3c',
    appId: '1:1084513530190:web:9aece578b5d3ea6a036e1f',
    messagingSenderId: '1084513530190',
    projectId: 'teste-3c5a3',
    authDomain: 'teste-3c5a3.firebaseapp.com',
    storageBucket: 'teste-3c5a3.firebasestorage.app',
    measurementId: 'G-P3JX0V4HGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbXziUuxtWtcYMpP6uK2RYe655Q8_acSg',
    appId: '1:1084513530190:android:6f6227e6096423b0036e1f',
    messagingSenderId: '1084513530190',
    projectId: 'teste-3c5a3',
    storageBucket: 'teste-3c5a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRL5-2EVzyO08wI2y_Wygg_ykrERtwqs',
    appId: '1:1084513530190:ios:50f54521421f9312036e1f',
    messagingSenderId: '1084513530190',
    projectId: 'teste-3c5a3',
    storageBucket: 'teste-3c5a3.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRL5-2EVzyO08wI2y_Wygg_ykrERtwqs',
    appId: '1:1084513530190:ios:50f54521421f9312036e1f',
    messagingSenderId: '1084513530190',
    projectId: 'teste-3c5a3',
    storageBucket: 'teste-3c5a3.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Cml1bGTaoH24MDMDQ83YWGJsFTkIe3c',
    appId: '1:1084513530190:web:17b75b821ce316e2036e1f',
    messagingSenderId: '1084513530190',
    projectId: 'teste-3c5a3',
    authDomain: 'teste-3c5a3.firebaseapp.com',
    storageBucket: 'teste-3c5a3.firebasestorage.app',
    measurementId: 'G-3CD73QH103',
  );

}